version: "3.8"

services:
  nginx:
    image: nginx:1.24.0-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/log:/var/log/nginx
      - ./certs:/etc/ssl
    networks:
      - medusa

  minio:
    image: minio/minio:latest
    ports:
      - 9001:9001
      - 9002:9002
    restart: unless-stopped
    command: server /data --console-address :9002 --address :9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DOMAIN=${MINIO_DOMAIN}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
    volumes:
      - minio:/data
    networks:
      - medusa

  meili:
    image: getmeili/meilisearch:v1.5
    ports:
      - 7700:7700
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_ENV=production
    volumes:
      - meili:/meili_data
    networks:
      - medusa

  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - medusa

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - medusa

volumes:
  minio:
  meili:
  postgres:
  redis:

networks:
  medusa:
    name: medusa
    external: true
